// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	htafc "github.com/vladislav-chunikhin/feed-fetcher/internal/provider/htafc"

	mock "github.com/stretchr/testify/mock"
)

// FeedProvider is an autogenerated mock type for the FeedProvider type
type FeedProvider struct {
	mock.Mock
}

type FeedProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *FeedProvider) EXPECT() *FeedProvider_Expecter {
	return &FeedProvider_Expecter{mock: &_m.Mock}
}

// GetLatestNews provides a mock function with given fields: ctx
func (_m *FeedProvider) GetLatestNews(ctx context.Context) (*htafc.NewListInformation, error) {
	ret := _m.Called(ctx)

	var r0 *htafc.NewListInformation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*htafc.NewListInformation, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *htafc.NewListInformation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*htafc.NewListInformation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeedProvider_GetLatestNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestNews'
type FeedProvider_GetLatestNews_Call struct {
	*mock.Call
}

// GetLatestNews is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FeedProvider_Expecter) GetLatestNews(ctx interface{}) *FeedProvider_GetLatestNews_Call {
	return &FeedProvider_GetLatestNews_Call{Call: _e.mock.On("GetLatestNews", ctx)}
}

func (_c *FeedProvider_GetLatestNews_Call) Run(run func(ctx context.Context)) *FeedProvider_GetLatestNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *FeedProvider_GetLatestNews_Call) Return(_a0 *htafc.NewListInformation, _a1 error) *FeedProvider_GetLatestNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FeedProvider_GetLatestNews_Call) RunAndReturn(run func(context.Context) (*htafc.NewListInformation, error)) *FeedProvider_GetLatestNews_Call {
	_c.Call.Return(run)
	return _c
}

// NewFeedProvider creates a new instance of FeedProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeedProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeedProvider {
	mock := &FeedProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
