// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

type Producer_Expecter struct {
	mock *mock.Mock
}

func (_m *Producer) EXPECT() *Producer_Expecter {
	return &Producer_Expecter{mock: &_m.Mock}
}

// PublishHtafcFeed provides a mock function with given fields: ctx, message
func (_m *Producer) PublishHtafcFeed(ctx context.Context, message []byte) error {
	ret := _m.Called(ctx, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Producer_PublishHtafcFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishHtafcFeed'
type Producer_PublishHtafcFeed_Call struct {
	*mock.Call
}

// PublishHtafcFeed is a helper method to define mock.On call
//   - ctx context.Context
//   - message []byte
func (_e *Producer_Expecter) PublishHtafcFeed(ctx interface{}, message interface{}) *Producer_PublishHtafcFeed_Call {
	return &Producer_PublishHtafcFeed_Call{Call: _e.mock.On("PublishHtafcFeed", ctx, message)}
}

func (_c *Producer_PublishHtafcFeed_Call) Run(run func(ctx context.Context, message []byte)) *Producer_PublishHtafcFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *Producer_PublishHtafcFeed_Call) Return(_a0 error) *Producer_PublishHtafcFeed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Producer_PublishHtafcFeed_Call) RunAndReturn(run func(context.Context, []byte) error) *Producer_PublishHtafcFeed_Call {
	_c.Call.Return(run)
	return _c
}

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
