apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed-service
  name: feed-service
  namespace: feed-service
spec:
  type: NodePort
  ports:
    - name: "feed-service"
      port: 8084
      targetPort: 8084
      nodePort: 31002
    - name: "feed-debug"
      port: 8086
      targetPort: 8086
      nodePort: 31003
  selector:
    app: feed-service
