apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: feed-service
spec:
  type: ClusterIP
  ports:
    - name: "mongodb-service"
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb
