apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed-service
  name: feed-service
  namespace: feed-service
spec:
  type: NodePort
  ports:
    - name: "feed-service"
      port: 8080
      targetPort: 8080
      nodePort: 31000
    - name: "feed-debug"
      port: 8082
      targetPort: 8082
      nodePort: 31001
  selector:
    app: feed-service
