apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: feed-transformer
spec:
  type: ClusterIP
  ports:
    - name: "rabbit-service"
      port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
