// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	feed "github.com/vladislav-chunikhin/feed-service/internal/repository/feed"
	feed0 "github.com/vladislav-chunikhin/feed-service/internal/service/feed"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockFeedService is a mock of FeedService interface.
type MockFeedService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServiceMockRecorder
}

// MockFeedServiceMockRecorder is the mock recorder for MockFeedService.
type MockFeedServiceMockRecorder struct {
	mock *MockFeedService
}

// NewMockFeedService creates a new mock instance.
func NewMockFeedService(ctrl *gomock.Controller) *MockFeedService {
	mock := &MockFeedService{ctrl: ctrl}
	mock.recorder = &MockFeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedService) EXPECT() *MockFeedServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockFeedService) GetByID(ctx context.Context, ID primitive.ObjectID) (*feed.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, ID)
	ret0, _ := ret[0].(*feed.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFeedServiceMockRecorder) GetByID(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFeedService)(nil).GetByID), ctx, ID)
}

// GetLatestArticles mocks base method.
func (m *MockFeedService) GetLatestArticles(ctx context.Context, cursor string, limit int) (*feed0.ArticlePaginationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestArticles", ctx, cursor, limit)
	ret0, _ := ret[0].(*feed0.ArticlePaginationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestArticles indicates an expected call of GetLatestArticles.
func (mr *MockFeedServiceMockRecorder) GetLatestArticles(ctx, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestArticles", reflect.TypeOf((*MockFeedService)(nil).GetLatestArticles), ctx, cursor, limit)
}
