apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed-fetcher
  name: feed-fetcher
  namespace: feed-fetcher
spec:
  type: NodePort
  ports:
    - name: "fetcher-service"
      port: 8080
      targetPort: 8080
      nodePort: 31000
    - name: "fetcher-debug"
      port: 8082
      targetPort: 8082
      nodePort: 31001
  selector:
    app: feed-fetcher
