apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: feed-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3.9-alpine
          name: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
#              value: "${RABBITMQ_USERNAME}"
              value: vlad
            - name: RABBITMQ_DEFAULT_PASS
#              value: "${RABBITMQ_PASSWORD}"
              value: sport
          ports:
            - containerPort: 5672
              name: rabbitmq
          livenessProbe:
            exec:
              command:
                - "rabbitmqctl"
                - "ping"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
