---
name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write # needed to create and update comments in PRs

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sport-news/feed-fetcher
            ${{ secrets.DOCKERHUB_USERNAME }}/sport-news/feed-service
            ${{ secrets.DOCKERHUB_USERNAME }}/sport-news/feed-transformer
          flavor: |
            latest=false
          tags: |
            type=sha,prefix=${{ github.ref }}-
            type=raw,value=${{ github.ref }}-${{ github.sha }}

          #      - name: Docker build
          #        uses: docker/build-push-action@v5
          #        with:
          #          push: false
          #          tags: ${{ steps.docker_meta.outputs.tags }}
          #          labels: ${{ steps.docker_meta.outputs.labels }}
          #          cache-from: type=gha
          #          cache-to: type=gha,mode=max
          #          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Docker build
        run: make build-images
        working-directory: deployment