---
name: 'Feed Service: Build, Test and Push'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'feed-service/**'
      - '.github/workflows/docker-build-feed-service.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'feed-service/**'
      - '.github/workflows/docker-build-feed-service.yaml'
  schedule:
    # re-run monthly to keep image fresh with upstream base images
    - cron: '0 12 15 * *'

jobs:
  # Building a test image #######################################################################
  build-test-image:
    name: Build Image for Testing
    runs-on: ubuntu-latest

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3