---
name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sport-news/feed-fetcher
            ${{ secrets.DOCKERHUB_USERNAME }}/sport-news/feed-service
            ${{ secrets.DOCKERHUB_USERNAME }}/sport-news/feed-transformer
          flavor: |
            latest=false
          tags: |
            type=sha,prefix=${{ github.ref }}-
            type=raw,value=${{ github.ref }}-${{ github.sha }}

      - name: Docker build
        run: |
          pwd
          make build-images